### ISSUE TITLE
Switch AAI als Login anbinden

### ISSUE THREAD

**Issue by peggimann** [puzzle/unilu-pruefungsabfrage#1]
Als Benutzer möchte ich gerne mein normales Uni Login verwenden. Dies erleichtert mir den Umgang mit der Applikation.

### Hinweise zur Implementierung
Anhand eines PoC wurde die Authentisierung mit SWITCH AAI implementiert und getestet. Die Erkenntnisse aus dem PoC sollen in das aktuelle Projekt einfliessen. Für den PoC ist es notwendig, lokal einen Shibboleth Service Provider (SP) aufzusetzen. Anhand der Anleitung unter [docker shibboleth sp](https://gitlab.puzzle.ch/cga/docker/unilu-docker-shibboleth-sp) kann der lokale SP aufgesetzt werden. Anhand der Anleitung unter [PoC Login](https://github.com/puzzle/unilu-pruefungsabfrage/tree/poc-login) kann die Authentisierung in der EFT Applikation konfiguriert und implementiert werden.

Folgende Themen sind im PoC behandelt:
- Einbindung SWITCH AAI (prod. Umgebung) und AAI Test (Testumgebung)
- Aufsetzen eines Docker Image für den Shibboleth Service Provider (SP)
- Konfiguration SP und Apache httpd (beides im Docker Image)
- Umstellung EFT Applikation auf SSL und AJP
- Konfiguration der Spring Boot Security und Implementierung Pre-Authenticated Security Filter, welches in der Security Filter Chain verwendet wird
- Beispiele zu unauthorisiertem und authorisiertem Zugriff (Home Page, EFT Page)
- einfachste Integration Tests, um die Funktionalität zu prüfen

Folgende Themen sind im PoC nicht (weiter) behandelt und werden in Folge-Stories abgearbeitet:
- [Testing](https://github.com/puzzle/unilu-pruefungsabfrage/issues/139): http vs. https in den Tests (Unit Tests, E2E Tests)
- [Testing](https://github.com/puzzle/unilu-pruefungsabfrage/issues/139): mocked vs. skipped Authentication in den Tests (Unit Tests, E2E Tests)
- [Bereiche festlegen](https://github.com/puzzle/unilu-pruefungsabfrage/issues/140): Verfeinerung der gesicherten / ungesicherten Bereiche ( host/eft vs. host/home)
- [Zertifikat](https://github.com/puzzle/unilu-pruefungsabfrage/issues/142): Offizielles Zertifikat und Public Key bestellen und einbinden
- [Konfiguration](https://github.com/puzzle/unilu-pruefungsabfrage/issues/141): Auslagerung der Konfiguration abklären (Konfig-Werte, Dateien / Zertifikate)
- [Delivery](https://github.com/puzzle/unilu-pruefungsabfrage/issues/143): Inhalt Docker Image(s) abklären

### Anforderungen
- Switch AAI ist hinterlegt als Login
- Aus dem Login wird unter anderem die Matrikelnummer erhalten, um sicherzustellen, dass die Prüfung nur von sich selber eingesehen werden können.
- Der SP ist ein Shibboleth Server, welcher den Authorization workflow handelt.

### Akzeptanzkriterien
- [ ] Die oben aufgeführeten Anforderungen sind Vollumfänglich und konsistent über das ganze Projekt implementiert
- [ ] Das feature ist sauber getested.

**Comment by MasterEvarior** [comment]
**Stand 11.10.2024**

I've made a couple of change in accordance with what @peggimann and I discussed.
- the base URL changed from `/etc` to just `/`
- the `/error` page is accessible without auth (this also means that all the ressources are accessible without auth) 

All pages are displayed correclty, with the correct styling applied. The `POST /search` endpoint does not work though and redirects to ` /error`.  

**TODOs:**
- [ ] make the search work again
- [ ] fix tests (do this last)

**Comment by RandomTannenbaum** [comment]
**Stand 11.10.2024**
Heute habe ich daran gearbeitet, dass die Suche wieder funktioniert. Ich habe dabei herausgefunden, dass die Suche eigentlich funktioniert. Was nicht funktioniert, ist die Methode, welche die Matrikelnummer des Benutzers auslesen soll.

Momentan erwarten wir, dass `SecurityContextHolder.getContext().getAuthentication()` eine Instanz von `AuthenticationUser` zurückgibt. Das ist jedoch nicht der Fall. Auf dem Objekt das wir erhalten ist zwar der Name gespeichert jedoch nicht direkt die Matrikelnummer.

Im POC konnte Christoph die Matrikelnummer des Benutzers im Frontend anzeigen. Das können wir auch. Wenn man das Attribut `th:text={matriculationNumber}` auf einem Element in einem Template setzt, dann wird die Matrikelnummer angezeigt. Ich habe jedoch noch nicht herausgefunden wo diese gesetzt wird bzw. woher diese kommt.

**Comment by RandomTannenbaum** [comment]
**Stand 14.10.2024**
Heute habe ich vor allem daran gearbeitet, dass die Suche wieder funktioniert. Schlussendlich gelang das Auslese der Matrikelnummer, indem wir eine custom UserData Klasse erstellt haben, auf der wir ein Feld für den AuthenticationUser erstellt haben. Diesen geben wir im login flow mit.

ToDo
- Mir ist aufgefallen, dass viele logs bei einem browser reload mehrfach auftauchen. Ich bin mir noch nicht sicher, ob dies das vorgesehene Verhalten ist. Deshalb gilt es dies noch herauszufinden.
- In den logs steht manchmal authenticating null. Ist das normal und kommt vielleicht einfach daher, dass wir pre-authentication haben?
- Tests wieder zum laufen bringen und e2e Tests deaktivieren (kommen im Folgeticket zurück)
- Security header Prüfung wieder zum laufen bringen.
- Über das gesamte Ticket drüberschauen, ob sonst noch etwas fehlt.

**Comment by RandomTannenbaum** [comment]
**Fragen**
- Was sollen Methoden wie getDetails() returnen? "n/a" wie bisher, null oder vielleicht etwas anderes?

**Comment by RandomTannenbaum** [comment]
**Stand 15.10.2024**
Heute habe ich als erstes mal die custom UserData Klasse vereinfacht und geschaut dass das Auslesen der Matrikelnummer korrekt geschieht. Danach habe ich über die Tests geschaut und die Tests sowie den zap scan in der pipeline gefixt. Ausserdem wird nun der korrekte Username angezeigt und der logout button funktioniert auch.

**Comment by pizzi-cato** [comment]
> **Fragen**
> 
> * Was sollen Methoden wie getDetails() returnen? "n/a" wie bisher, null oder vielleicht etwas anderes?
> * Welche Methoden in /config sollen getestet werden?

CG: die Frage ist etwas heikel im Bereich der Security und muss mit dem Spring Security Framework abgestimmt werden. Generell gilt:

- null, falls (einfaches) Attribut nicht gesetzt ist
- leere Collection, falls diese nicht befüllt worden ist
- im Falle von "authenticated" sollte immer das Authentication Object zurückgegeben werden; im Falle von "unauthenticated" und unterstützten URLs (unauthorizedUrls) ein anonymes Authentication Object
- im Falle von getDetails() oder getCredentials() kann auch null zurückgegeben werden, sofern dies im Framework nicht zur ereuten Authorisierung oder gar zum Abbruch (Error) führt.

**Comment by RandomTannenbaum** [comment]
**Stand 16.10.2024**
Heute habe ich mit Giannin nochmal über das feature drübergeschaut und begonnen das auszubessern oder zu erweitern was noch fehlt.

- Die Rückgabewerte von Klassenvariablen die wir nicht brauchen oder preisgeben wollen ist jetzt immer null, mit Ausnahme von getUsername(), welche standardmässig "n/a" zurückgibt, da diese nicht null sein darf.
- Wir haben uns dazu entschieden alle bereiche der Applikation zu sichern. Das heisst auch die error page ist ohne login nicht erreichbar. Das haben wir gemacht, weil errors im Login ohnehin nicht von dieser error page angezeigt werden können und ohne eingeloggt zu sein kann der user auch nicht auf die Applikation zugreifen, also auch keinen Fehler von der login page angezeigt bekommen.
- Ich habe ausserdem noch die Tests erweitert. Es gibt jetzt erste AuthenticationUser und ShibbolethRequestAuthenticationFilter tests.

**Comment by MasterEvarior** [comment]
**Stand: 17.10.2024**
Ich habe noch die fehlenden Tests hinzugefügt, die Logs analyisiert und den Code soweit aufgeräumt das er ready für ein PR-Review ist.

**Comment by RandomTannenbaum** [comment]
**Stand 18.10.2024**
Heute habe nochmal über das Ticket drübergeschaut und es hat ein erstes Review stattgefunden. Ich habe nun begonnen die ersten conversations zu resolven.
