### ISSUE TITLE
Download single file styling

### ISSUE THREAD

**Issue by pizzi-cato** [puzzle/unilu-pruefungsabfrage#103]
Als Kunde möchte ich ein einheitliches Layout der App haben, das das Entwicklungsteam mit dem Kunden abgesprochen hat.

### Anforderungen
- Die Buttons zum download einer einzelnen Prüfung  der Text welcher sich auf diese bezieht ist anhand der folgenden Mockups gestyled.
![Image](https://github.com/user-attachments/assets/b51e8762-deb2-43c0-87c2-a8687946763a)

### Akzeptanzkriterien
- [x] Die aufgeführten Anforderungen sind alle erfüllt.
- [x] Die Tests sind entsprechend angepasst.

**Comment by Miguel7373** [comment]
### Stand 3.10.2024
Ich habe bereits das meiste gestylt und Tests dafür geschrieben.

Es sollte nur noch geschaut werden, ob man in der Box das Bild so stylen kann, ohne Position absolute zu benutzen, damit der Text dann auch einen Zeilenumbruch macht und nicht hinter das Bild geht.

Ebenfalls funktioniert der Frontend formatter nicht bei mir, daher sollte man noch alles formatieren lassen.

### To-do
- [ ] Styling des PDF-Images
- [ ] Überprüfung, ob noch Tests fehlen
- [ ] Frontend Formatieren

**Comment by ManuelMoeri** [comment]
## Stand 04.10.2024
Grundsätzlich wurde fast alles erledigt was noch zu erledigen war. Noch zu tun ist das overlapping welches Miguel auch beschrieben hat. Ich habe einige verschiedene sachen ausprobiert aber habe es nicht geschafft das der Text trotzdem noch mittig ist.

Dies passiert natürlich nur wenn der Name des faches extrem lang ist.
![image](https://github.com/user-attachments/assets/c2b77fe1-a4f6-4257-93c0-9237178c1a2d)
