### ISSUE TITLE
Kontakt Seite

### ISSUE THREAD

**Issue by peggimann** [puzzle/unilu-pruefungsabfrage#125]
Als User möchte ich eine Kontakt Seite die übersichtlich ist und mir weiterhilft falls ich auf ein Problem stosse.

### Styling & Inhalt
Marco hat uns folgende Informationen für die Kontakt Seite gemailed:
![image](https://github.com/user-attachments/assets/449dbbdd-efbd-4a91-b74b-23b6d54f3d8b)

### Anforderungen
- Ein grobes Design wurde erstellt und von Paco approved
- Sämtliche Informationen die uns Marco gegeben hat werden auf der Seite dargestellt
- Das Farbschema der Uni wurde berücksichtigt

### Akzeptanzkriterien
- [ ] Sämtliche Anforderungen wurden erfüllt
- [ ] Tests wurden ergänzt (E2E & Controller-Tests)

**Comment by ManuelMoeri** [comment]
### Stand 10.10.2024
Das Feature der Kontakt Seite ist soweit beendet.  Die Route wurde implementiert & ein Controllertest dazu geschrieben. Ein kleines Design wurde umgesetzt & Grundsätzliche Tests dazu geschrieben.  Im moment warte ich noch auf ein Feedback von Marco da wir ja keine Styling vorgaben hatten. Das Antwort-Mail werde ich, @RandomTannenbaum oder @MasterEvarior erhalten.

### ToDo
- [ ] Falls Änderungsvorschläge von Marco vorhanden sind, umsetzen.
- [ ] Tests anpassen -> Failen im moment noch
- [ ] Code cleanup

**Comment by ManuelMoeri** [comment]
### Stand 16.10.2024
Marco hat uns am Montag noch ein kleines design geschickt wie er es gerne haben möchte.
![image](https://github.com/user-attachments/assets/273943e9-2d4d-46d4-b951-a98226a2f75f)
