### ISSUE TITLE
AAI: Konfiguration der Komponenten

### ISSUE THREAD

**Issue by pizzi-cato** [puzzle/unilu-pruefungsabfrage#141]
Als Betreiber der EFT Applikation möchte ich die Konfiguration der beteiligten Komponenten (Apache Web Server, Shibboleth Service Provider, Reverse Proxy, EFT Application) mit ausgelagerten Dateien (z.B. Zertifikate) und / oder Umgebungsvariablen bewerkstelligen können (z.B. URLs, Ports). Dabei muss beachtet werden, dass keine sensitiven Daten im github Repository gespeichert werden dürfen.

Dies ist eine Folg-Story zu [Switch AAI als Login anbinden](https://github.com/puzzle/unilu-pruefungsabfrage/issues/1).

### Anforderungen

- Es ist festgelegt, welche Konfiguration wie und wo erfolgt.
- Die Pfadangaben bzw. Umgebungsvariablen sind angepasst.
- Es lassen sich Prod-, Staging- und Dev-Umgebung unabhängig voneinander konfigurieren.
- Die Tests können in einer Dev-/Test-Umgebung konfiguriert und ausgeführt werden.
- Es gibt ein `docker-compose.yml`, welches die Anforderungen umsetzt
- Das `docker-compose.yml` nimmt die Images aus dem Repository und builded sie nicht selber  

### Akzeptanzkriterien

- [ ] obige Anforderungen sind alle erfüllt
- [ ] die Konfiguration für Test- und Prod-Umgebung sind nachgeführt
- [x] die Dokumentation der EFT Applikation ist nachgeführt
- [ ] das ` docker-compose.yml` existiert gemäss Vorgaben

**Comment by RandomTannenbaum** [comment]
**Stand 25.10.2024**
Ich habe heute begonnen das docker-compose zu bauen und die config files der Applikation mit env-Variablen zu bearbeiten, damit die Applikation von aussen konfiguriert werden kann.

ToDo:
- Ich muss mir noch überlegen wo genau ich die Secrets für die lokale und die prod Umgebung ablege, bzw. wie ich sie voneinander abtrenne, da wir ja nun auch den Service-Provider im Repo haben werden.
- Wenn ich eine gute Struktur aufgebaut habe und ich auf den Service Provider rebasen konnte, muss ich noch die beiden compose files (lokal und prod) verbessern und zum laufen bringen.

**Comment by RandomTannenbaum** [comment]
**Stand 28.10.2024**
Ich habe heute die Ordnerstruktur und die docker compose files überarbeitet.
- Unter `/shibboleth/secrets` gibt es jetzt wieder einen `test` und einen `prod unterordner`.
- Das `dev` docker compose im `root` directory buildet  das docker image für den service provider jedes mal neu und startet wie bisher über einen simplen mvn command die Applikation.
- Das `prod` docker compose zieht sich die, über die tag variable, angegebene Version der docker images vom Github registry und startet sie.

Momentane Probleme und ToDo:
- [ ] Den alten cert directory entfernen
- [ ] Das readme updaten
- [ ] Wenn man das dev compose beendet funktioniert nach dem Neustart der sp nicht mehr korrekt. Er scheint nicht mehr erreichbar zu sein. Er funktioniert erst wieder wenn man `docker compose rm` ausführt und danach neustartet, was das image neu buildet.
- [ ] Momentan kann ich das prod compose nicht starten, da ich noch den Fehler erhalte, dass das Passwort für den keystore falsch sei. Ich habe schon mehrmals den keystore neu erstellt. Das Passwort wird eigentlich über eine env Variable gesetzt. Vielleicht wird diese noch nicht korrekt an das Image weitergegeben.

**Comment by RandomTannenbaum** [comment]
**Stand 29.10.2024**
Ich habe jetzt die beiden docker compose files zum laufen gebracht und die Applikation funktioniert.

Jetzt muss ich noch die Dokumentation im readme update. Ausserdem laufen momentan alle container noch mit network_mode host und ich kann noch schauen welche Ports ich freigeben muss, damit ich mit einem normalen bridge network arbeiten kann.

**Comment by RandomTannenbaum** [comment]
**ToDo**
- [ ] Make name of keystore an env var
- [ ] Move docker compose file to root dir
- [ ] Fix health check and zap test
