### ISSUE TITLE
Sonar Cube Pipeline

### ISSUE THREAD

**Issue by Miguel7373** [puzzle/unilu-pruefungsabfrage#37]
Als Entwickler möchte ich sicher stellen, dass der Code sauber und möglichst ohne Bugs ist. Dafür ist eine Pipeline nötig damit es nicht immer manuel gemacht werden muss.

### Anforderungen
- Die aktuelle Codequality soll in einer Pipeline auf SonarCube gepushed werden.

### Akzeptanzkriterien

- [x] Bei jedem Merge auf den Main Branch wird die Code Qualität in Sonar Cube mit einer Pipeline aktualisiert.

### ToDo
- [x] Fragen welches user token wir verwenden werden um uns zu authentifizieren.
- [x] Testen

**Comment by Miguel7373** [comment]
### Stand 20.8.24

Die Pipeline läuft nicht da ein github workflow nicht im internal network ist und daher keinen zugriff auf das puzzle sonar hat.

**Comment by ManuelMoeri** [comment]
### Stand 22.08.2024
Heute habe ich den command auf der pipeline gefixt, jedoch funktioniert es noch immer nicht. Lokal kann man 1:1 den gleichen command ausführen und es funktioniert einwandfrei. Ich habe es sogar mit dem Token aus dem GitHub secret Lokal getestet. Zu diesem Zeitpunkt warte ich noch auf die Antwort von /mid ob das Whitelisting und ähnliches funktioniert hat.

Ich habe morgen ÜK aber werde den ganzen Tag auf dem Puzzle-Chat erreichbar sein. Falls ich eine Antwort erhalte leite ich diese unverzüglich weiter.

**ToDo**
- [ ] Antwort von /mid abwarten & weiterhin mit ihnen schauen bis die Pipeline funktioniert
- [ ] Die '-e' flag aus dem command in der GitHub Action entfernen (Ist für das debuging)
- [ ] Den Branch #29  ebenfalls aus der GitHub Action entfernen. Der Branch ist im moment noch drin das die Pipeline auf dem Branch aus Testzwecken läuft.

**Comment by RandomTannenbaum** [comment]
**Update**
Für die Pipeline scheint der Host `sonar-githubactions.puzzle.ch` zu sein.
