### ISSUE TITLE
Style Stories

### ISSUE THREAD

**Issue by peggimann** [puzzle/unilu-pruefungsabfrage#43]
Um das Auftreten der Applikation in die Umgebung der Universität Luzern zu integrieren müssen wir sicherstellen, dass die Applikation entsprechend gestyled ist. Dafür verwenden wir den Style Guide der Uni Luzern.

### Anorderungen:
Die folgenden Stories sind erfasst und beschrieben für die Umsetzung:
- [x] Header --> Seite 12-13 im Style Guide, Logos --> Ticket #59 
- [x] Schriftart wird lokal bereitgestellt --> Seite 9, 14, 16 im Style Guide --> Ticket #68 
- [x] Favicon und name der Applikation --> Seite 13 im Style Guide --> Ticket #58 
- [x] Farbschema für Links und Buttons --> Seite 20-21 im Style Guide --> Ticket #61 
- [ ] Footer --> Einfacher Footer evt mit infos zur Uni oder Referenz auf Puzzle, zusätzlich ersichtlich die Version des Tools. --> Ticket #62 

### Hinweise
Style Guide: https://files.puzzle.ch/s/LXM23pmbK27AeM5
Logos: https://files.puzzle.ch/s/9A3aJbdTc9JgoTX
Screenshot Liste: https://files.puzzle.ch/s/fkoqCNCtK74Z2t3
Screenshot Prüfungslaufnummer Feld: https://files.puzzle.ch/s/HS4yyNd4fgg5SCN

### Akzeptanzkriterien
- [ ] Die Stories sind erfasst
- [ ] Es ist beschrieben oder gezeigt wie das Endresultat aussehen soll.
- [ ] Die Hilfsmittel für die Umsetzung sind gegeben (Seitennummern im Style Guide, Screenshots, Logos).
