### ISSUE TITLE
CI Pipelines erststellen für Unit Test und E2E Tests

### ISSUE THREAD

**Issue by peggimann** [puzzle/unilu-pruefungsabfrage#5]
Als Entwickler will ich sicherstellen, dass nur Code in den Main Branch gemerged werden kann, welcher die Test passed. Dafür wollen wir Pipelines einrichten.

### Anforderungen
- Die Tests werden automatisch bei jedem Push auf jedem Branch, sowohl main wie auch feature Branches ausgeführt.
- Die Testing Pipelines sollen failen, wenn die Tests failen
- Die Testing Pipelines sollen failen, wenn die Code Coverage nicht erfüllt ist.
- Es soll nicht in den Main branch gemerged werden können, falls eine Pipeline nicht passed.

### Akzeptanzkriterien
- [ ] Die oben aufgeführten Pipelines sind als GithubWorkflow im entsprechenden ordner erstellt
- [ ] Mergen wird verhindert, wenn die Pipelines failen
- [ ] Die Pipelines failen nach den oben definierten Bedingungen

### ToDo
- [x] Pipelines des OKR Tools anschauen
- [x] Unterschied zwischen 'mvn clean verify' und 'mvn test' anschauen
- [x] Pipeline für allgemeines Testing aufsetzen
- [x] Testen ob die Pipeline failt wenn tests failen
- [x] Testen ob der Branch mit failenden Tests in Main gemerged werden könnte
- [x] Review durch Lernender
- [ ] Review von Paco
