### ISSUE TITLE
CI Pipeline erstellen für Ablegen im Artifactory

### ISSUE THREAD

**Issue by peggimann** [puzzle/unilu-pruefungsabfrage#6]
Als Entwickler möchte ich einen möglichst simplen Weg haben, um dem Kunden die aktuelle Version der Applikation zukommen zu lassen. Damit kann der Kunde sicherstellen, das die Applikation immer auf dem aktuellsten Stand ist. 

### Anforderungen
- Wenn wir ein Feature in den Main Branch mergen, und die Tests erfolgreich sind, soll eine getaggte Version davon im privaten Harbor Projekt hinterlegt werden
- Es existiert ein Workflow, welchen wir von Hand ausführen können um ein Release zu bauen. Dabei soll eine Version der Applikation gebaut werden, welche anschliessend getestet wird und falls diese Tests erfolgreich sind soll diese Version im Public Repository dem Kunden zur verfügung gestellt werden. (Release)
- Bei einem Release soll das Image mit dem Commit Hash getagged werden, welcher dem Startbranch entspricht. 
- Weiter soll in Github ein Release Branch erstellt werden. 

### Akzeptanzkriterien
- [x] Bei einem Merge auf Main soll vollautomatisch ein Image im private Repo in Harbor erstellt werden.
- [x] Wir können manuell eine Release Pipeline anstossen
- [x] Bei der Release Pipeline wird ein Release gebaut und wie oben beschrieben getagged.
- [x] Nur getestete Images können in den Repos abgelegt werden.

**Comment by RandomTannenbaum** [comment]
**Hinweise**
Wie man das Docker Image buildet kann man sich [hier](https://github.com/puzzle/okr/blob/main/.github/workflows/staging-deploy-action.yml#L47) orientieren. Das Builden mit Dockerfile kann man leider nicht direkt in den Buildprozess integrieren.

**Comment by nevio18324** [comment]
**Stand 20.8.2024** 
Alle akzeptanzkriterien erfüllt, dass einzige ist dass, beim Release docker Image workflow noch ein Weg fehlt die Version zu überprüfen/bestätigen.

**Comment by RandomTannenbaum** [comment]
**Stand 21.08.2024**
Anforderungen:

On-Merge (private harbor project):
- Bei einem Merge auf Main wird das Image gebuildet und die E2E laufen gegen den laufenden Docker container.
- Wenn die Tests erfolgreich sind wird das gebuildete Image auf das private Harbor Projekt gepusht. Dabei soll es getagged werden in der Form: <version>.<short-commit-hash>

On-Release (public harbor project):
- Für einen release wird eine Pipeline manuell ausgeführt
- Der Workflow liest als erstes die Version der Applikation aus dem pom.xml aus
- In einem Input feld wird diese Version vorgeschlagen. Dort kann die Version dann manuell geändert werden, falls dies nötig ist
- Die neue Version wird in das pom.xml geschrieben und auf die Changes auf den main branch gepusht
- Der Workflow checkt den neuen commit aus und buildet das Image
- Das gebuildete Image wird gestartet und die E2E-Tests werden gegen dieses ausgeführt
- Wenn das erfolgreich war, wird ein Release erstellt, der in der Form <version>.<short-commit-hash> getagged wird
- Nach dem Release wird das Image auf das public harbor repository gepusht

**Comment by RandomTannenbaum** [comment]
**ToDo**
- [ ] Pipeline testen
- [ ] Sbom des releases auf public Projekt im deptrack pushen
- [ ] Repo aufräumen (Releases löschen usw.)

**Comment by RandomTannenbaum** [comment]
**Stand 23.08.2024**
Ich habe heute schon einen grossen Teil der Pipeline aufgebaut. Momentan sieht der Ablauf wie folgt aus:
- Checkout
- Setup (JDK, Node, Docker Buildx)
- Neue snapshot Version aus Input setzen
- Das Jar builden ohne die E2E-Tests dabei auszuführen
- Ein Tar-Archiv builden, welches das Docker-Image enthält
- Aus dem Tar-Archiv das Image laden
- Den Docker-Container Starten
- Per NPM Cypress installieren und die E2E-Tests auf den laufenden Container ausführen
- Einen Release erstellen
- Das Docker-Image auf das Harbor-Repo pushen
- Ein sbom erstellen und auf deptrack pushen

Um das ganze zu testen, habe ich die Pipeline kopiert, ein zweites File erstellt und dieses on-push ausgeführt. Die Inputs die so fehlen habe ich in ENV-Variablen gehardcoded.

Es hat jedoch noch einige kleinere Dinge die fehlen oder die man noch überdenken sollte:
- Für die E2E-Tests installiere ich momentan noch Cypress per NPM. Ich denke es muss möglich sein den JUnit-Test, welcher die E2E-Tests per Testcontainers ausführt, zu starten, ohne die ganze Applikation mit hochzuziehen. Da der Container auf dem unsere Applikation läuft ganz normal den Port 8080 exposed, sollte es eigentlich kein Problem sein, die Cypress Tests so direkt auszuführen.
- Für den Push auf das Harbor repo, verwenden wir momentan noch die build-and-push-action. Diese buildet jedoch das Image jedes Mal neu. Da wir das Image aber ja schon gebuildet haben, sollte der normale `docker push` command genügen.
- Die Create Release Action die wir verwenden ist schon seit 2021 archived und unmaintained. Ich habe bisher noch keine wirklich akutellere Alternative gefunden. Ein Weg wäre das Github CLI in der Action zu verwenden, über welches man auch releases erstellen kann.

**Comment by RandomTannenbaum** [comment]
**Stand 26.08.2024**
Ich habe heute viele meiner Punkte die ich im letzten Kommentar benannt habe, behoben.

Namentlich habe ich zuerst den release gefixt, indem ich nun in der Pipeline zuerst einen Release-Tag auf den richtigen Branch pushe und mit dem Github-CLI dann von diesem Tag aus einen Release erstelle.

Das Problem mit harbor mit Harbor habe ich behoben, indem ich einfach direkt das vorher gebuildete Image mit `docker image push` pushe.

Danach habe ich noch versucht herauszufinden, wie es möglich ist, den JUnit Test, welcher für die E2E-Tests zuständig ist, ohne Web-Environment zu starten, damit dieser dann auf den laufenden Container zugreift. Damit habe ich bisher jedoch noch keinen Erfolg gehabt.

**Comment by RandomTannenbaum** [comment]
**Stand 28.08.2024**
Ich habe heute die ganze Pipeline noch einmal überarbeitet und alfällige Fehler behoben. Grundsätzlich funktioniert die Pipeline. Sie kann das Docker image E2E-Testen, einen Release per Github CLI erstellen (tagging in der pipeline funktioniert momentan nur mit commits die schon auf dem main branch sind), sie kann das Image korrekt auf Harbor pushen und es wird auch ein versionierter Dependency-Track Eintrag erstellt.

Was allerdings noch fehlt ist das Versioning.

Hierfür habe ich auch bzgl. maven release pluginnachgeforscht. Diesem muss man die Repo URL mitgeben und es pusht im Prozess automatisch den Tag, bumpt die Version usw. Hier kann man jedoch nur direkt auf den neuesten commit gehen, da das pushen der neuen Version sonst natürlich merge Konflikte geben würde. Deshalb habe ich mir überlegt dass es vielleicht doch gar nicht so schlecht wäre, release branches von den gewünschten Commits aus zu erstellen, da wir so diese Problem beheben. Hierfür könnte man auch das maven release plugin verwenden. Aber in unserer pipeline wäre momentan der Aufwand geringer wenn wir den branch einfach manuell erstellen. Das setzen der vorher eingegebenen Version ist auch ohne maven release plugin kein Problem.

**Comment by RandomTannenbaum** [comment]
**Stand 04.09.2024**
Das Ticket ist bereit für ein erstes Review, wir müssen aber noch schauen was wir mit dem Versioning machen, da sich dies ja immer noch mit dem wählen eines älteren Commits für den Release beisst.

Ausserdem wäre ein tieferer Blick in die Nutzung des Maven Release Plugins gut. Ich habe mich momentan dagegen entschieden, da es nur releases vom aktuellen commit oder einem neuen Branch erlaubt.

**Comment by RandomTannenbaum** [comment]
**Stand 10.09.2024**
Blocked weil ich nächste Woche (18.09.) ein Meeting mit Yannik Dällenbach habe, wo wir die Struktur der Pipeline besprechen. Er hat auch schon ein eigenes Review auf dem Branch gemacht.

**Comment by RandomTannenbaum** [comment]
**Stand 18.09.2024**
Nach dem Gespräch mit Yanick Dällenbach haben sich vor allem folgende Punkte zum Besprechen herauskristalisiert:
- Es wäre besser wenn man keine Input felder für den Workflow verwenden würde. So könnte man den Workflow on tag ausführen und wenn der Tag z.b. ein bestimmtes Format hat, von diesem Tag aus dann den Release erstellen.
- Die Semver Version sollte auch nicht über einen Input oder sonstiges gesetzt werden. Hier wurde vorgeschlagen einfach den Release manuel vorzubereiten indem man eine Pullrequest mit der gewünschten Version usw. erstellt, diese merged und von dort dann den Release erstellt.
- Momentan starte ich das gebuildete Image in der Pipeline noch mit docker run. Hier war der Vorschlag das Image auch mit testcontainers zu starten bzw. kann man Testcontainers ein Dockerfile geben welches es dann direkt buildet. -> Daran habe ich schon begonnen  zu arbeiten.
- Es wurde vorgeschlagen die Images statt auf Harbor direkt auf den Image Registry des Github repos zu pushen. So ist alles an einem Platz.
- Ausserdem habe ich momentan noch zwei Workflows, einen on merge und einen release, bei welchen viel Redundanz vorhanden ist. Dafür kann ich einen base workflow schreiben, der von beiden referenziert wird. Ausserdem kam hier noch die Frage auf warum wir überhaupt zwei Registries haben (private und public) wenn das Projekt sowieso open-source ist. -> (Vielleicht könnte man vom Release aus sogar auf das dazugehörige Image verweisen)

**Comment by RandomTannenbaum** [comment]
- Dokumentation im Readme

**Comment by RandomTannenbaum** [comment]
- Mit tags
- Testing ohne build
- Image auf github

**Comment by RandomTannenbaum** [comment]
**Stand 01.10.2024**
Heute habe ich die restlichen Änderungen umgesetzt. Das image wird jetzt auf das github registry gepusht. Ausserdem habe ich ein kleines script erstellt, das automatisch einen korrekten Tag erstellt und so den Release anstösst.
Ich habe Yannick Dällenbach für ein weiteres review angefragt.

**Comment by RandomTannenbaum** [comment]
**ToDo**
Die Pipeline wurde von Yannick Dällenbach approved. Das einzige was noch fehlt ist das versioning auf dependency track. Hier haben wir uns momentan entschieden die major und minor Version einzubeziehen, also die ersten zwei Zahlen der semver Version. Dabei sollten wir [diese Stelle aus dem dependency track guide auf PuzzleDocs beachten](https://docs.puzzle.ch/qm-guide/latest/security/dependencychecks.html#_beispiele_f%C3%BCr_sbom_generation).
