### ISSUE TITLE
Dependency Track einrichten

### ISSUE THREAD

**Issue by peggimann** [puzzle/unilu-pruefungsabfrage#7]
Im späteren Verlauf des Supports, möchten wir möglichst schnell feststellen, was die aktuellen Security issues in unserem Projekt sind. Dafür verwenden wir den Deptrack von Puzzle: https://deptrack.ocp.cloudscale.puzzle.ch/dashboard

### Anforderungen
- Es existieren zwei Projekte im Deptrack von Puzzle für die UNI Luzern
- Dabei ist ein Projekt für den Main Branch und ein Projekt für das ausgelieferte Image beim Kunden
- Die Deptracks werden automatisch generiert bei den jeweiligen Merges.

### Akzeptanzkriterien
- [x] Wenn in den Main Branch gemerged wird, wird in der Pipeline automatisch der Deptrack Staging erstellt
- [ ] Wenn wir den Release ausführen wird in der Pipeline automatisch der Deptrack Prod erstellt.

**Comment by ManuelMoeri** [comment]
**Stand 14.08.2024**
Der grundsätzliche Code steht. Im pom.xml wurde das CycloneDX Plugin eingebunden und installiert. Vorgegangen bin ich [hiermit](https://docs.puzzle.ch/qm-guide/latest/security/dependencychecks.html) + mit der neusten version die ich auf Maven Repository gefunden habe. Die Funktion des plugins wurde in eine Pipeline integriert. Dieses file heisst 'dependency-track-deploy-action.yml'.

Im moment ist das Ticket BLOCKED weil uns der API Key fehlt um es auf den Dependency Tracker zu pushen. Diese werden laut Doku von /security verwaltet. Im moment jedoch hat Mark Ferien und darum ist niemand da. Als ersatz wurde Yannik geschrieben, jedoch blieb die Antwort bis jetzt aus.

**Comment by RandomTannenbaum** [comment]
**Stand 16.08.2024**
Der push auf das Dependency-Track wenn eine Pull-Request gemerged wird ist nun implementiert. Der Push auf das release-repository wird später mit dem release-pipeline Ticket implementiert.

Ein zweites Projekt habe ich auch schon erstellt auf Dependency-Track. Dieses muss von Sys noch für das BBT Team freigeschalten werden.

Hinweis: Dependency-Track scheint momentan nicht mit CycloneDX Version 1.5 klarzukommen, welche mit CycloneDX-Maven-Plugin Version 2.8 eingeführt wurde. Da wir die aktuellste Version des Plugins (2.8.1) verwenden ist es zwingend nötig im pom.xml in der Plugin configuration die `<schemaVersion>` auf 1.4 zu setzen.

**Comment by RandomTannenbaum** [comment]
**ToDo**
- [ ] Es existieren zwei Projekte im Deptrack von Puzzle für die UNI Luzern
- [ ] Dabei ist ein Projekt für den Main Branch und ein Projekt für das ausgelieferte Image beim Kunden
- [ ] Die Deptracks werden automatisch generiert bei den jeweiligen Merges.
