### ISSUE TITLE
Filesystem mit Initialdaten aufsetzen

### ISSUE THREAD

**Issue by peggimann** [puzzle/unilu-pruefungsabfrage#8]
Als Entwickler möchte ich die Möglichkeit die Funktionalität meiner Applikation einfach zu Testen. Dazu möchten wir das Filesystem wo die Prüfungen abgelegt sind Simulieren.

### Anforderungen
- Das Filesystem hat einen inital Ordner in diesem Ordner wird das Filesystem abgelegt.
~~Durch die Application Properties kann definiert werden wo dieser Folder genau liegt.~~
- Im Rootfolder, existieren mehrere Folders mit Modulbezeichnungen (Strafrecht, Zivilrecht,...) mindestens 5
- Pro Modulfolder liegen mehrere Prüfungen, dabei haben diese das folgende Format `24000_19103103` dabei bilden die ersten 5 Ziffern die Prüfungslaufnummer und die letzten 8 die Matrikel Nr. 
- Pro Modulfolder sind mehrere verschiedene Pdf, mit unterschiedlichen Matrikel Nr und Prüfungslaufnummern

### Akzeptanzkriterien
- [ ] Die Anforderungen sind alle erfüllt

~~Durch die Application Properties kann definiert werden wo dieser Folder genau liegt.~~

### ToDo
- [x] Root ordner für filesystem erstellen
- [x] Unterordner mit verschiedenen Modulbezeichnungen erstellen
- [x] Jedes Modul mit entsprechenden PDF Files füllen
- [x] File namen überprüfen
- [ ] Review

**Comment by ManuelMoeri** [comment]
**Stand 12.08.2024**

Alle Nötigen Ordner erstellt und auch schon angefangenn PDFs  zu erstellen. Hier ist der fortschritt:
Alle diese Files wären für das erste Modul

[11000_99990000.pdf](https://github.com/user-attachments/files/16586712/11000_99990000.pdf)
[22000_7777888
[22000_55556666.pdf](https://github.com/user-attachments/files/16586864/22000_55556666.pdf)
8.pdf](https://github.com/user-attachments/files/16586800/22000_77778888.pdf)
[11111_33334444.pdf](https://github.com/user-attachments/files/16586932/11111_33334444.pdf)
[11111_11112222.pdf](https://github.com/user-attachments/files/16586977/11111_11112222.pdf)

Hier ist das Libreoffice file welches ich immer abändere:
[Changing_PDF.odt](https://github.com/user-attachments/files/16586561/Changing_PDF.odt)

Dies sind alle Nummern die bereits verwendet geworden sind:
11111_11112222
11111_33334444
22000_55556666
22000_77778888
11000_99990000

**Comment by RandomTannenbaum** [comment]
**Stand 13.08.2024**
Grundsätzlich steht ein Filesystem. Jedoch sind diverese Testcases nicht abdeckbar mit dem momentanen System. Dazu gehört Beispielsweise:
- Mehrere Prüfungen mit gleicher Matrikelnummer im selben Fach
- Mehrere Prüfungen mit gleicher Prüfungsnummer im selben Fach

**Comment by ManuelMoeri** [comment]
> **Stand 13.08.2024** Grundsätzlich steht ein Filesystem. Jedoch sind diverese Testcases nicht abdeckbar mit dem momentanen System. Dazu gehört Beispielsweise:
> 
>     * Mehrere Prüfungen mit gleicher Matrikelnummer im selben Fach
> 
>     * Mehrere Prüfungen mit gleicher Prüfungsnummer im selben Fach

Beide diese Punkte wurden beachtet und dazugehörie PDFs wurden in dem **Ethik** und dem **Soziologie** folder erstellt. Die anderen 3 Module wurden nicht veränderet.

Die namen aller files wurden noch einmal überprüft. Die PR ist ready for review.

**Comment by RandomTannenbaum** [comment]
**Stand 16.08.2024**
Ich habe das Filesystem auf die neuen Fächer `Privatrecht, Strafrecht, Öffentliches Recht, Handels und Gesellschaftsrecht` angepasst. Ausserdem habe ich die Spezialfälle die wir testen wollen Abgedeckt. (Zwei Personen mit der selben Matrikelnummer und zwei Tests mit der selben Prüfungsnummer.)
